version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "p0stgr@s_dev"
      POSTGRES_DB:       "eagle_eye_dev"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
    image: msa/licensing-service
    ports:
      - "8080:8000"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://localhost:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"

